prefix setup bug
C:/Users/User/AppData/Local/Programs/Python/Python311/python.exe c:/Users/User/Documents/GitHub/RP-Utilities/bot.py
Traceback (most recent call last):
  File "c:\Users\User\Documents\GitHub\RP-Utilities\bot.py", line 59, in <module>
    Bot().run(bot_token.return_token())
    ^^^^^
  File "c:\Users\User\Documents\GitHub\RP-Utilities\bot.py", line 19, in __init__
    command_prefix = self.prefix_setup(),
                     ^^^^^^^^^^^^^^^^^^^
TypeError: Bot.prefix_setup() missing 1 required positional argument: 'ctx'